### PR TITLE
[MS-25] Fixes missing CloudFront distributions

### PR DESCRIPTION
**Pull request by hermanmedsleuth**
whitelabel/core.py - correct
- .discover_services() - check for 'ServiceEndpoint', instead of assuming it exists

ref: #17, [MS-25]

### to Test
- install in a test infrastructure
- verify that AWS CloudFront distributions are created.

[MS-25]: https://medsleuth.atlassian.net/browse/MS-25

### CODE REVIEW

**Comment by jyaucs** [comment]
aws-whitelabel  branch `Issues/w.17` is pre-merged to `pre-dev-210`. Branch `pre-dev-210` is attached to infra `j229` and the PR changes are being updated (ready in ~30 mins) for developer pipeline testing.

**Comment by jyaucs** [comment]
A key error is triggered on the dryrun step of `s4-client` pipeline:

[codebuild log](https://console.aws.amazon.com/codesuite/codebuild/785321780735/projects/DryRunCB-Gk0MF33HK1Vv/build/DryRunCB-Gk0MF33HK1Vv%3A6c802dde-43c6-41ba-958f-71d8944159fb/?region=us-east-1)

```
[Container] 2020/09/18 04:21:13 Running command chmod +x $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.py
--
108 |  
109 | [Container] 2020/09/18 04:21:13 Running command $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh
110 | DRY RUN ENGAGED.......
111 | ==[ Fetching service details.. ]==============
112 | demo (s3 com-medsleuth-j229-demo): s3://com-medsleuth-j229-demo
113 | static (s3 com-medsleuth-j229-static): s3://com-medsleuth-j229-static/{$subdomain}.{$domain}
114 | redirectMobileB3 (lambda-arn cf-j229:RedirectMobileB3LambdaFunctionQualifiedArn): arn:aws:lambda:us-east-1:785321780735:function:cf-j229-redirectMobileB3:18
115 | bjs (serverless bjs-j229): Traceback (most recent call last):
116 | File "/codebuild/output/src650/src/s3/01/aws-whitelabel.py", line 9, in <module>
117 | main()
118 | File "/codebuild/output/src650/src/s3/01/whitelabel/core.py", line 1158, in main
119 | discover_services(yaml.get('ServiceConfig', yaml.get('serviceconfig')))
120 | File "/codebuild/output/src650/src/s3/01/whitelabel/core.py", line 124, in discover_services
121 | if svcStack and 'Outputs' in svcStack[0]:
122 | KeyError: 0
123 |  
124 | [Container] 2020/09/18 04:21:14 Command did not exit successfully $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh exit status 1
125 | [Container] 2020/09/18 04:21:14 Phase complete: BUILD State: FAILED
126 | [Container] 2020/09/18 04:21:14 Phase context status code: COMMAND_EXECUTION_ERROR Message: Error while executing command: $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh. Reason: exit status 1
```

**Comment by hermanmedsleuth** [comment]
Thx. @jyaucs.  More debugging is required. I will be pushing my updates directly to branch `pre-dev-210`.

**Comment by jyaucs** [comment]
merging to dev for fixing issue https://github.com/medsleuthinc/infrastructure/issues/845

**Review by jyaucs — COMMENTED** [review]
looks good

**Pull request merged**
