### PR TITLE
PLS DO NOT MERGE - PR Review for Cherry-picking Needed Changes from Tested Branch release/v2.15 to HOTFIX Branch release/hotfix/v2.14.1

### PR DESCRIPTION
**Pull request by jyaucs**
Related PRs:
   - https://github.com/medsleuthinc/b.java/pull/252
   - https://github.com/medsleuthinc/b.cfg/pull/1295
   - https://github.com/medsleuthinc/BREEZE/pull/4525
   - https://github.com/medsleuthinc/infrastructure/pull/853
   - https://github.com/medsleuthinc/react-survey/pull/1069

### CODE REVIEW

**Comment by hermanmedsleuth** [comment]
No changes to this repo are required unless the persistence transition updates are installed.

**Comment by jyaucs** [comment]
Updating infra `pre-prod` with aws-whitelabel branch `release/hotfix/v2.14.1` (cloned from branch `master`), an index error is triggered on step `dry-run` of pipeline `s4-client`:

[codebuild log](https://console.aws.amazon.com/codesuite/codebuild/785321780735/projects/DryRunCB-yMWuZMIgE493/build/DryRunCB-yMWuZMIgE493%3Ae9da1ff3-8078-4ad2-8ab9-bd1079e09dde/?region=us-east-1)

```
[Container] 2020/12/04 23:45:42 Running command $CODEBUILD_SRC_DIR_Whitelabel/aws-whitelabel.sh
--
110 | DRY RUN ENGAGED.......
111 | ==[ Fetching service details.. ]==============
112 | demo (s3 com-medsleuth-pre-prod-demo): s3://com-medsleuth-pre-prod-demo
113 | static (s3 com-medsleuth-pre-prod-static): s3://com-medsleuth-pre-prod-static/{$subdomain}.{$domain}
114 | redirectMobileB3 (lambda-arn cf-preprod:RedirectMobileB3LambdaFunctionQualifiedArn): arn:aws:lambda:us-east-1:785321780735:function:cf-preprod-redirectMobileB3:15
115 | bjs (serverless bjs-preprod): Traceback (most recent call last):
116 | File "/codebuild/output/src715/src/s3/01/aws-whitelabel.py", line 9, in <module>
117 | main()
118 | File "/codebuild/output/src715/src/s3/01/whitelabel/core.py", line 1144, in main
119 | discover_services(yaml.get('ServiceConfig', yaml.get('serviceconfig')))
120 | File "/codebuild/output/src715/src/s3/01/whitelabel/core.py", line 123, in discover_services
121 | url = ([item for item in l if item['OutputKey'] == 'ServiceEndpoint'][0]['OutputValue'])
122 | IndexError: list index out of range
```

**Comment by hermanmedsleuth** [comment]
The error indicates that the `bjs` service configuration is not available, which in turn means that changes relating to the persistence transition, which remove the no longer needed `bjs` service configuration, are in place in the `pre-prod` infrastructure.

Is the `pre-prod` infrastructure deployed fresh from the current release (master) branches, and subsequently updated? ...or is it in some leftover state from a previous deployment?

**Comment by jyaucs** [comment]
Yeah, I think infra `pre-prod` in some way is still using the previous deployment branch set of `Issues/j.229`. I will try a remove and recreate sequence to re-update infra `pre-prod` with the following branch set:

```
# Branches (hotfix release v2.14.1)
BranchForB3=release/hotfix/v2.14.1
BranchForB3Admin=release/v2.9
BranchForGraphUpload=release/hotfix/v2.14.1
BranchForBREEZE=release/hotfix/v2.14.1
BranchForCfg=release/hotfix/v2.14.1
BranchForInfrastructure=release/hotfix/v2.14.1
BranchForWhitelabel=release/hotfix/v2.14.1
BranchForJava=release/hotfix/v2.14.1
BranchForLambda=release/hotfix/v2.14.1
BranchForMeta=release/v2.9
BranchForScanner=release/v2.9
BranchForTestSuite=release/hotfix/v2.14.1
BranchForSurveyService=release/hotfix/v2.14.1
BranchForStaticSites=release/v2.14
BranchForMedSurvey=release/v2.9
BranchForDjango=release/hotfix/v2.14.1
BranchForB2req=release/hotfix/v2.14.1
```

**Comment by jyaucs** [comment]
The recreation of infra `pre-prod` removed the above exception. :) @hermanmedsleuth thx

**Pull request closed without merging**
